/*global systemDictionary:true */
'use strict';

systemDictionary = {
    Authentication: {
        en: 'Authentication',
        de: 'Authentifizierung',
        ru: 'Аутентификация',
        pt: 'Autenticação',
        nl: 'Authenticatie',
        fr: 'Authentification',
        it: 'Autenticazione',
        es: 'Autenticación',
        pl: 'Uwierzytelnianie',
        'zh-cn': '认证',
    },
    'Get it from https://dev.myuplink.com/apps': {
        en: 'Get it from https://dev.myuplink.com/apps',
        de: 'Gibts auf https://dev.myuplink.com/apps',
        ru: 'Получите его на сайте https://dev.myuplink.com/apps',
        pt: 'Obtenha-o em https://dev.myuplink.com/apps',
        nl: 'Ga naar https://dev.myuplink.com/apps',
        fr: "Vous pouvez l'obtenir à l'adresse suivante https://dev.myuplink.com/apps",
        it: 'Richiedetelo a https://dev.myuplink.com/apps',
        es: 'Consíguelo en https://dev.myuplink.com/apps',
        pl: 'Pobierz ze strony https://dev.myuplink.com/apps',
        'zh-cn': '从 https://dev.myuplink.com/apps 获取',
    },
    'Does not need to be changed. You can use https://sebilm.github.io/ioBroker.myuplink/myuplink.html': {
        en: 'Does not need to be changed. You can use https://sebilm.github.io/ioBroker.myuplink/myuplink.html',
        de: 'Muss nicht geändert werden. Es kann https://sebilm.github.io/ioBroker.myuplink/myuplink.html verwendet werden.',
        ru: 'Does not need to be changed. You can use https://sebilm.github.io/ioBroker.myuplink/myuplink.html',
        pt: 'Does not need to be changed. You can use https://sebilm.github.io/ioBroker.myuplink/myuplink.html',
        nl: 'Does not need to be changed. You can use https://sebilm.github.io/ioBroker.myuplink/myuplink.html',
        fr: 'Does not need to be changed. You can use https://sebilm.github.io/ioBroker.myuplink/myuplink.html',
        it: 'Does not need to be changed. You can use https://sebilm.github.io/ioBroker.myuplink/myuplink.html',
        es: 'Does not need to be changed. You can use https://sebilm.github.io/ioBroker.myuplink/myuplink.html',
        pl: 'Does not need to be changed. You can use https://sebilm.github.io/ioBroker.myuplink/myuplink.html',
        'zh-cn': 'Does not need to be changed. You can use https://sebilm.github.io/ioBroker.myuplink/myuplink.html',
    },
    'Click here to generate the Auth Code on myUplink.': {
        en: 'Click here to generate the Auth Code on myUplink.',
        de: 'Hier klicken, um den Auth-Code auf myUplink zu generieren.',
        ru: 'Click here to generate the Auth Code on myUplink.',
        pt: 'Click here to generate the Auth Code on myUplink.',
        nl: 'Click here to generate the Auth Code on myUplink.',
        fr: 'Click here to generate the Auth Code on myUplink.',
        it: 'Click here to generate the Auth Code on myUplink.',
        es: 'Click here to generate the Auth Code on myUplink.',
        pl: 'Click here to generate the Auth Code on myUplink.',
        'zh-cn': 'Click here to generate the Auth Code on myUplink.',
    },
    'Paste your Auth Code here.': {
        en: 'Paste your Auth Code here.',
        de: 'Den Auth-Code hier einfügen.',
        ru: 'Paste your Auth Code here.',
        pt: 'Paste your Auth Code here.',
        nl: 'Paste your Auth Code here.',
        fr: 'Paste your Auth Code here.',
        it: 'Paste your Auth Code here.',
        es: 'Paste your Auth Code here.',
        pl: 'Paste your Auth Code here.',
        'zh-cn': 'Paste your Auth Code here.',
    },
    Settings: {
        en: 'Settings',
        de: 'Einstellungen',
        ru: 'Настройки',
        pt: 'Definições',
        nl: 'Instellingen',
        fr: 'Paramètres',
        it: 'Impostazioni',
        es: 'Ajustes',
        pl: 'Ustawienia',
        'zh-cn': '设置',
    },
    'Refresh interval': {
        en: 'Refresh interval',
        de: 'Aktualisierungsintervall',
        ru: 'Интервал обновления',
        pt: 'Intervalo de atualização',
        nl: 'Vernieuwingsinterval',
        fr: 'Intervalle de rafraîchissement',
        it: 'Intervallo di aggiornamento',
        es: 'Intervalo de actualización',
        pl: 'Interwał odświeżania',
        'zh-cn': '刷新间隔',
    },
    'Time in minutes of fetching data from myUplink.': {
        en: 'Time in minutes of fetching data from myUplink.',
        de: 'Zeit in Minuten für den Abruf von Daten von myUplink.',
        ru: 'Время в минутах получения данных из myUplink.',
        pt: 'Tempo em minutos de obtenção de dados do myUplink.',
        nl: 'Tijd in minuten voor het ophalen van gegevens van myUplink.',
        fr: "Durée en minutes de l'extraction des données de myUplink.",
        it: 'Tempo in minuti di recupero dei dati da myUplink.',
        es: 'Tiempo en minutos de obtención de datos de myUplink.',
        pl: 'Czas w minutach pobierania danych z myUplink.',
        'zh-cn': '从 myUplink 获取数据的时间（分钟）。',
    },
    Language: {
        en: 'Language',
        de: 'Sprache',
        ru: 'Язык',
        pt: 'Língua',
        nl: 'Taal',
        fr: 'Langue',
        it: 'Lingua',
        es: 'Idioma',
        pl: 'Język',
        'zh-cn': '语言',
    },
    English: {
        en: 'English',
        de: 'Englisch',
        ru: 'Английский язык',
        pt: 'Inglês',
        nl: 'Engels',
        fr: 'Anglais',
        it: 'Inglese',
        es: 'Inglés',
        pl: 'Angielski',
        'zh-cn': '英语',
    },
    German: {
        en: 'German',
        de: 'Deutsch',
        ru: 'Немецкий язык',
        pt: 'Alemão',
        nl: 'Duits',
        fr: 'Allemand',
        it: 'Tedesco',
        es: 'Alemán',
        pl: 'Niemiecki',
        'zh-cn': '德国',
    },
    Swedish: {
        en: 'Swedish',
        de: 'Schwedisch',
        ru: 'Swedish',
        pt: 'Sueco',
        nl: 'Zweeds',
        fr: 'Suédois',
        it: 'Svedese',
        es: 'Sueco',
        pl: 'Szwedzki',
        'zh-cn': '瑞典语',
    },
    'The language for naming the data objects.': {
        en: 'The language for naming the data objects.',
        de: 'Die Sprache für die Benennung der Datenobjekte.',
        ru: 'Язык для именования объектов данных.',
        pt: 'A linguagem para nomear os objectos de dados.',
        nl: 'De taal voor het benoemen van de gegevensobjecten.',
        fr: 'Le langage pour nommer les objets de données.',
        it: 'Il linguaggio per la denominazione degli oggetti di dati.',
        es: 'El lenguaje para nombrar los objetos de datos.',
        pl: 'Język nazewnictwa obiektów danych.',
        'zh-cn': '命名数据对象的语言。',
    },
};
