/*global systemDictionary:true */
'use strict';

systemDictionary = {
    Authentication: {
        en: 'Authentication',
        de: 'Authentifizierung',
        ru: 'Аутентификация',
        pt: 'Autenticação',
        nl: 'Authenticatie',
        fr: 'Authentification',
        it: 'Autenticazione',
        es: 'Autenticación',
        pl: 'Uwierzytelnianie',
        uk: 'Аутентифікація',
        'zh-cn': '认证',
    },
    'Get it from https://dev.myuplink.com/apps': {
        en: 'Get it from https://dev.myuplink.com/apps',
        de: 'Gibts auf https://dev.myuplink.com/apps',
        ru: 'Получите его на сайте https://dev.myuplink.com/apps',
        pt: 'Obtenha-o em https://dev.myuplink.com/apps',
        nl: 'Ga naar https://dev.myuplink.com/apps',
        fr: "Vous pouvez l'obtenir à l'adresse suivante https://dev.myuplink.com/apps",
        it: 'Richiedetelo a https://dev.myuplink.com/apps',
        es: 'Consíguelo en https://dev.myuplink.com/apps',
        pl: 'Pobierz ze strony https://dev.myuplink.com/apps',
        uk: 'Отримайте її за посиланням https://dev.myuplink.com/apps',
        'zh-cn': '从 https://dev.myuplink.com/apps 获取',
    },
    'Does not need to be changed. You can use https://sebilm.github.io/ioBroker.myuplink/myuplink.html': {
        en: 'Does not need to be changed. You can use https://sebilm.github.io/ioBroker.myuplink/myuplink.html',
        de: 'Muss nicht geändert werden. Es kann https://sebilm.github.io/ioBroker.myuplink/myuplink.html verwendet werden.',
        ru: 'Не требует изменений. Вы можете использовать https://sebilm.github.io/ioBroker.myuplink/myuplink.html',
        pt: 'Não precisa de ser alterado. Pode utilizar https://sebilm.github.io/ioBroker.myuplink/myuplink.html',
        nl: 'Hoeft niet te worden gewijzigd. U kunt https://sebilm.github.io/ioBroker.myuplink/myuplink.html gebruiken.',
        fr: "Il n'est pas nécessaire de le modifier. Vous pouvez utiliser https://sebilm.github.io/ioBroker.myuplink/myuplink.html",
        it: 'Non è necessario modificarlo. È possibile utilizzare https://sebilm.github.io/ioBroker.myuplink/myuplink.html',
        es: 'No es necesario cambiarlo. Puede utilizar https://sebilm.github.io/ioBroker.myuplink/myuplink.html',
        pl: 'Nie trzeba go zmieniać. Można użyć https://sebilm.github.io/ioBroker.myuplink/myuplink.html',
        uk: 'Не потребує змін. Можна використовувати https://sebilm.github.io/ioBroker.myuplink/myuplink.html.',
        'zh-cn': '无需更改。您可以使用 https://sebilm.github.io/ioBroker.myuplink/myuplink.html',
    },
    'Click here to generate the Auth Code on myUplink.': {
        en: 'Click here to generate the Auth Code on myUplink.',
        de: 'Hier klicken, um den Auth-Code auf myUplink zu generieren.',
        ru: 'Нажмите здесь, чтобы сгенерировать Auth-код на myUplink.',
        pt: 'Clique aqui para gerar o código de autenticação no myUplink.',
        nl: 'Klik hier om de Auth-Code op myUplink te genereren.',
        fr: "Cliquez ici pour générer le code d'authentification sur myUplink.",
        it: 'Fare clic qui per generare il codice di autorizzazione su myUplink.',
        es: 'Haga clic aquí para generar el Auth Code en myUplink.',
        pl: 'Kliknij tutaj, aby wygenerować Auth Code na myUplink.',
        uk: 'Натисніть тут, щоб згенерувати код авторизації на myUplink.',
        'zh-cn': '单击此处在 myUplink 上生成 Auth Code 。',
    },
    'Paste your Auth Code here.': {
        en: 'Paste your Auth Code here.',
        de: 'Den Auth-Code hier einfügen.',
        ru: 'Вставьте сюда свой код авторизации.',
        pt: 'Cole o seu código de autenticação aqui.',
        nl: 'Plak hier je Auth Code.',
        fr: "Collez votre code d'authentification ici.",
        it: 'Incollare qui il codice di autorizzazione.',
        es: 'Pegue aquí su Auth Code.',
        pl: 'Wklej tutaj swój Auth Code.',
        uk: 'Вставте код доступу сюди.',
        'zh-cn': '在此处粘贴您的 Auth Code.',
    },
    Settings: {
        en: 'Settings',
        de: 'Einstellungen',
        ru: 'Настройки',
        pt: 'Definições',
        nl: 'Instellingen',
        fr: 'Paramètres',
        it: 'Impostazioni',
        es: 'Ajustes',
        pl: 'Ustawienia',
        uk: 'Налаштування',
        'zh-cn': '设置',
    },
    'Refresh interval': {
        en: 'Refresh interval',
        de: 'Aktualisierungsintervall',
        ru: 'Интервал обновления',
        pt: 'Intervalo de atualização',
        nl: 'Vernieuwingsinterval',
        fr: 'Intervalle de rafraîchissement',
        it: 'Intervallo di aggiornamento',
        es: 'Intervalo de actualización',
        pl: 'Interwał odświeżania',
        uk: 'Інтервал оновлення',
        'zh-cn': '刷新间隔',
    },
    'Time in minutes of fetching data from myUplink.': {
        en: 'Time in minutes of fetching data from myUplink.',
        de: 'Zeit in Minuten für den Abruf von Daten von myUplink.',
        ru: 'Время в минутах получения данных из myUplink.',
        pt: 'Tempo em minutos de obtenção de dados do myUplink.',
        nl: 'Tijd in minuten voor het ophalen van gegevens van myUplink.',
        fr: "Durée en minutes de l'extraction des données de myUplink.",
        it: 'Tempo in minuti di recupero dei dati da myUplink.',
        es: 'Tiempo en minutos de obtención de datos de myUplink.',
        pl: 'Czas w minutach pobierania danych z myUplink.',
        uk: 'Час у хвилинах для отримання даних з myUplink.',
        'zh-cn': '从 myUplink 获取数据的时间（分钟）。',
    },
    Language: {
        en: 'Language',
        de: 'Sprache',
        ru: 'Язык',
        pt: 'Língua',
        nl: 'Taal',
        fr: 'Langue',
        it: 'Lingua',
        es: 'Idioma',
        pl: 'Język',
        uk: 'Мова',
        'zh-cn': '语言',
    },
    English: {
        en: 'English',
        de: 'Englisch',
        ru: 'Английский язык',
        pt: 'Inglês',
        nl: 'Engels',
        fr: 'Anglais',
        it: 'Inglese',
        es: 'Inglés',
        pl: 'Angielski',
        uk: 'Англійська мова',
        'zh-cn': '英语',
    },
    German: {
        en: 'German',
        de: 'Deutsch',
        ru: 'Немецкий язык',
        pt: 'Alemão',
        nl: 'Duits',
        fr: 'Allemand',
        it: 'Tedesco',
        es: 'Alemán',
        pl: 'Niemiecki',
        uk: 'Німецька',
        'zh-cn': '德国',
    },
    Swedish: {
        en: 'Swedish',
        de: 'Schwedisch',
        ru: 'Swedish',
        pt: 'Sueco',
        nl: 'Zweeds',
        fr: 'Suédois',
        it: 'Svedese',
        es: 'Sueco',
        pl: 'Szwedzki',
        uk: 'Шведська',
        'zh-cn': '瑞典语',
    },
    'The language for naming the data objects.': {
        en: 'The language for naming the data objects.',
        de: 'Die Sprache für die Benennung der Datenobjekte.',
        ru: 'Язык для именования объектов данных.',
        pt: 'A linguagem para nomear os objectos de dados.',
        nl: 'De taal voor het benoemen van de gegevensobjecten.',
        fr: 'Le langage pour nommer les objets de données.',
        it: 'Il linguaggio per la denominazione degli oggetti di dati.',
        es: 'El lenguaje para nombrar los objetos de datos.',
        pl: 'Język nazewnictwa obiektów danych.',
        uk: "Мова для іменування об'єктів даних.",
        'zh-cn': '命名数据对象的语言。',
    },
    'Parameter data': {
        en: 'Parameter data',
        de: 'Parameter-Daten',
        ru: 'Данные о параметрах',
        pt: 'Dados dos parâmetros',
        nl: 'Parametergegevens',
        fr: 'Données de paramètres',
        it: 'Dati dei parametri',
        es: 'Datos de los parámetros',
        pl: 'Dane parametrów',
        uk: 'Дані параметрів',
        'zh-cn': '参数数据',
    },
    'Retrieve parameter data': {
        en: 'Retrieve parameter data',
        de: 'Parameter-Daten abrufen',
        ru: 'Получение данных о параметрах',
        pt: 'Recuperar dados de parâmetros',
        nl: 'Parametergegevens ophalen',
        fr: 'Récupérer les données des paramètres',
        it: 'Recuperare i dati dei parametri',
        es: 'Recuperar datos de parámetros',
        pl: 'Pobieranie danych parametrów',
        uk: 'Отримати дані параметрів',
        'zh-cn': '读取参数数据',
    },
    'Parameter data will be retrieved and added to the object tree.': {
        en: 'Parameter data will be retrieved and added to the object tree.',
        de: 'Parameter-Daten werden abgerufen und zum Objektbaum hinzugefügt.',
        ru: 'Данные о параметрах будут извлечены и добавлены в дерево объектов.',
        pt: 'Os dados do parâmetro serão recuperados e adicionados à árvore de objectos.',
        nl: 'Parametergegevens worden opgehaald en toegevoegd aan het objectscherm.',
        fr: "Les données des paramètres seront récupérées et ajoutées à l'arbre des objets.",
        it: "I dati dei parametri verranno recuperati e aggiunti all'albero degli oggetti.",
        es: 'Los datos de los parámetros se recuperarán y se añadirán al árbol de objetos.',
        pl: 'Dane parametrów zostaną pobrane i dodane do drzewa obiektów.',
        uk: "Дані параметрів отримуються і додаються до дерева об'єктів.",
        'zh-cn': '参数数据将被检索并添加到对象树中。',
    },
    'Add object with the raw JSON data': {
        en: 'Add object with the raw JSON data',
        de: 'Objekt mit den JSON-Rohdaten hinzufügen',
        ru: 'Добавьте объект с необработанными данными JSON',
        pt: 'Adicionar objeto com os dados JSON em bruto',
        nl: 'Object toevoegen met de ruwe JSON-gegevens',
        fr: 'Ajouter un objet avec les données JSON brutes',
        it: 'Aggiungere un oggetto con i dati JSON grezzi',
        es: 'Añadir objeto con los datos JSON sin procesar',
        pl: 'Dodaj obiekt z nieprzetworzonymi danymi JSON',
        uk: "Додавання об'єкта з необробленими даними JSON",
        'zh-cn': '添加包含原始 JSON 数据的对象',
    },
    'An object containing the received data as a JSON string is added to the object tree.': {
        en: 'An object containing the received data as a JSON string is added to the object tree.',
        de: 'Ein Objekt, das die empfangenen Daten als JSON-String enthält, wird dem Objektbaum hinzugefügt.',
        ru: 'Объект, содержащий полученные данные в виде строки JSON, добавляется в дерево объектов.',
        pt: 'Um objeto que contém os dados recebidos como uma cadeia JSON é adicionado à árvore de objectos.',
        nl: 'Een object met de ontvangen gegevens als een JSON-string wordt toegevoegd aan het objectscherm.',
        fr: "Un objet contenant les données reçues sous forme de chaîne JSON est ajouté à l'arbre des objets.",
        it: "Un oggetto contenente i dati ricevuti come stringa JSON viene aggiunto all'albero degli oggetti.",
        es: 'Se añade al árbol de objetos un objeto que contiene los datos recibidos como cadena JSON.',
        pl: 'Obiekt zawierający otrzymane dane jako ciąg JSON jest dodawany do drzewa obiektów.',
        uk: "Об'єкт, що містить отримані дані у вигляді JSON-рядка, додається до дерева об'єктів.",
        'zh-cn': '一个包含接收到的 JSON 字符串数据的对象会被添加到对象树中。',
    },
    Notifications: {
        en: 'Notifications',
        de: 'Benachrichtigungen',
        ru: 'Уведомления',
        pt: 'Notificações',
        nl: 'Meldingen',
        fr: 'Notifications',
        it: 'Notifiche',
        es: 'Notificaciones',
        pl: 'Powiadomienia',
        uk: 'Сповіщення',
        'zh-cn': '通知',
    },
    'Retrieve active notifications': {
        en: 'Retrieve active notifications',
        de: 'Aktive Benachrichtigungen abrufen',
        ru: 'Получение активных уведомлений',
        pt: 'Recuperar notificações activas',
        nl: 'Actieve meldingen ophalen',
        fr: 'Récupérer les notifications actives',
        it: 'Recuperare le notifiche attive',
        es: 'Recuperar notificaciones activas',
        pl: 'Pobieranie aktywnych powiadomień',
        uk: 'Aktive Benachrichtigungen abrufen',
        'zh-cn': '检索活动通知',
    },
    'Active notifications will be retrieved and added to the object tree.': {
        en: 'Active notifications will be retrieved and added to the object tree.',
        de: 'Aktive Benachrichtigungen werden abgerufen und dem Objektbaum hinzugefügt.',
        ru: 'Активные уведомления будут извлечены и добавлены в дерево объектов.',
        pt: 'As notificações activas serão recuperadas e adicionadas à árvore de objectos.',
        nl: 'Actieve meldingen worden opgehaald en toegevoegd aan het objectscherm.',
        fr: "Les notifications actives seront récupérées et ajoutées à l'arbre des objets.",
        it: "Le notifiche attive verranno recuperate e aggiunte all'albero degli oggetti.",
        es: 'Las notificaciones activas se recuperarán y se añadirán al árbol de objetos.',
        pl: 'Aktywne powiadomienia zostaną pobrane i dodane do drzewa obiektów.',
        uk: "Активні сповіщення витягуються і додаються до дерева об'єктів.",
        'zh-cn': '活动通知将被检索并添加到对象树中。',
    },
    'Add object with active notifications as raw JSON': {
        en: 'Add object with active notifications as raw JSON',
        de: 'Objekt mit aktiven Benachrichtigungen als rohes JSON hinzufügen',
        ru: 'Добавьте объект с активными уведомлениями в виде необработанного JSON',
        pt: 'Adicionar objeto com notificações activas como JSON em bruto',
        nl: 'Object met actieve meldingen toevoegen als onbewerkte JSON',
        fr: 'Ajouter un objet contenant des notifications actives sous forme de JSON brut',
        it: "Aggiungere l'oggetto con le notifiche attive come JSON grezzo",
        es: 'Añadir objeto con notificaciones activas como JSON sin procesar',
        pl: 'Dodaj obiekt z aktywnymi powiadomieniami jako nieprzetworzony JSON',
        uk: "Додавання об'єкта з активними сповіщеннями у вигляді сирого JSON",
        'zh-cn': '以原始 JSON 格式添加包含活动通知的对象',
    },
    'An object containing the received active notifications as a JSON string is added to the object tree.': {
        en: 'An object containing the received active notifications as a JSON string is added to the object tree.',
        de: 'Ein Objekt, das die empfangenen aktiven Benachrichtigungen als JSON-String enthält, wird dem Objektbaum hinzugefügt.',
        ru: 'В дерево объектов добавляется объект, содержащий полученные активные уведомления в виде JSON-строки.',
        pt: 'Um objeto que contém as notificações activas recebidas como uma cadeia JSON é adicionado à árvore de objectos.',
        nl: 'Een object met de ontvangen actieve meldingen als een JSON-string wordt toegevoegd aan de objectboom.',
        fr: "Un objet contenant les notifications actives reçues sous forme de chaîne JSON est ajouté à l'arbre des objets.",
        it: "Un oggetto contenente le notifiche attive ricevute come stringa JSON viene aggiunto all'albero degli oggetti.",
        es: 'Se añade al árbol de objetos un objeto que contiene las notificaciones activas recibidas en forma de cadena JSON.',
        pl: 'Obiekt zawierający otrzymane aktywne powiadomienia jako ciąg JSON jest dodawany do drzewa obiektów.',
        uk: "Об'єкт, що містить активні сповіщення, отримані у вигляді JSON-рядка, додається до дерева об'єктів.",
        'zh-cn': '对象树中会添加一个对象，该对象以 JSON 字符串形式包含已收到的活动通知。',
    },
    'Group parameter data by received category': {
        en: 'Group parameter data by received category',
        de: 'Parameter-Daten nach empfangener Kategorie gruppieren',
        ru: 'Группировка данных параметров по полученным категориям',
        pt: 'Agrupar datos de parámetros por categoría recibida',
        nl: 'Groepeer parametergegevens per ontvangen categorie',
        fr: 'Regroupement des données de paramètres par catégorie de réception',
        it: 'Raggruppare i dati dei parametri per categoria di ricezione',
        es: 'Agrupar datos de parámetros por categoría recibida',
        pl: 'Grupowanie danych parametrów według odebranej kategorii',
        uk: 'Згрупуйте дані параметрів за отриманою категорією',
        'zh-cn': '按接收类别分组参数数据',
    },
    'The parameter data is grouped by the categories received.': {
        en: 'The parameter data is grouped by the categories received.',
        de: 'Die Parameter-Daten werden nach den empfangenen Kategorien gruppiert.',
        ru: 'Данные о параметрах группируются в соответствии с полученными категориями.',
        pt: 'Os dados dos parâmetros são agrupados de acordo com as categorias recebidas.',
        nl: 'De parametergegevens worden gegroepeerd volgens de ontvangen categorieën.',
        fr: 'Les données des paramètres sont regroupées en fonction des catégories reçues.',
        it: 'I dati dei parametri vengono raggruppati in base alle categorie ricevute.',
        es: 'Los datos de los parámetros se agrupan según las categorías recibidas.',
        pl: 'Dane parametrów są grupowane zgodnie z otrzymanymi kategoriami.',
        'zh-cn': '参数数据根据收到的类别进行分组。',
    },
    '': {
        en: '',
        de: '',
        ru: '',
        pt: '',
        nl: '',
        fr: '',
        it: '',
        es: '',
        pl: '',
        'zh-cn': '',
    },
};
