/**
 * myUplink Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Country } from '../models/Country';

/**
 * Address model.
 */
export class Address {
    /**
     * Default state of empty Address
     */
    'id'?: string | null;
    /**
     * LineOne
     */
    'lineOne'?: string | null;
    /**
     * LineTwo
     */
    'lineTwo'?: string | null;
    /**
     * PostalCode
     */
    'postalCode'?: string | null;
    /**
     * City
     */
    'city'?: string | null;
    /**
     * Region
     */
    'region'?: string | null;
    'country'?: Country;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
        {
            name: 'id',
            baseName: 'id',
            type: 'string',
            format: '',
        },
        {
            name: 'lineOne',
            baseName: 'lineOne',
            type: 'string',
            format: '',
        },
        {
            name: 'lineTwo',
            baseName: 'lineTwo',
            type: 'string',
            format: '',
        },
        {
            name: 'postalCode',
            baseName: 'postalCode',
            type: 'string',
            format: '',
        },
        {
            name: 'city',
            baseName: 'city',
            type: 'string',
            format: '',
        },
        {
            name: 'region',
            baseName: 'region',
            type: 'string',
            format: '',
        },
        {
            name: 'country',
            baseName: 'country',
            type: 'Country',
            format: '',
        },
    ];

    /**
     * Returns the attribute type map for the Address model.
     */
    static getAttributeTypeMap(): Array<{ name: string; baseName: string; type: string; format: string }> {
        return Address.attributeTypeMap;
    }

    /**
     * Constructs an instance of the Address class.
     */
    public constructor() {}
}
