/**
 * myUplink Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export enum AggregationMethod {
    Max = 'Max',
    Min = 'Min',
    Sum = 'Sum',
    Average = 'Average',
    Median = 'Median',
    Diff = 'Diff',
    None = 'None',
}
