/**
 * myUplink Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AidMode } from '../models/AidMode';

export class AidModeResponseModel {
    'aidMode'?: AidMode;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
        {
            name: 'aidMode',
            baseName: 'aidMode',
            type: 'AidMode',
            format: '',
        },
    ];

    static getAttributeTypeMap() {
        return AidModeResponseModel.attributeTypeMap;
    }

    public constructor() {}
}
