/**
 * myUplink Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { AidMode } from '../models/AidMode';

/**
 * Represents the response model for AidMode.
 */
export class AidModeResponseModel {
    'aidMode'?: AidMode;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
        {
            name: 'aidMode',
            baseName: 'aidMode',
            type: 'AidMode',
            format: '',
        },
    ];

    /**
     * Returns the attribute type map for AidModeResponseModel.
     */
    static getAttributeTypeMap(): Array<{ name: string; baseName: string; type: string; format: string }> {
        return AidModeResponseModel.attributeTypeMap;
    }

    /**
     * Constructs a new instance of the AidModeResponseModel class.
     */
    public constructor() {}
}
