/**
 * myUplink Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Status } from '../models/Status';

export class AlarmStatus {
    'status'?: Status;
    /**
     * Date of the alarm.
     */
    'datetime'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
        {
            name: 'status',
            baseName: 'status',
            type: 'Status',
            format: '',
        },
        {
            name: 'datetime',
            baseName: 'datetime',
            type: 'number',
            format: 'int32',
        },
    ];

    static getAttributeTypeMap(): Array<{ name: string; baseName: string; type: string; format: string }> {
        return AlarmStatus.attributeTypeMap;
    }

    public constructor() {}
}
