/**
 * myUplink Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Alarm } from '../models/Alarm';

/**
 * Alarms paged.
 */
export class AlarmsPaged {
    /**
     * Page.
     */
    'page'?: number;
    /**
     * Items per page.
     */
    'itemsPerPage'?: number;
    /**
     * Num items.
     */
    'numItems'?: number;
    /**
     * Notifications.
     */
    'notifications'?: Array<Alarm> | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
        {
            name: 'page',
            baseName: 'page',
            type: 'number',
            format: 'int32',
        },
        {
            name: 'itemsPerPage',
            baseName: 'itemsPerPage',
            type: 'number',
            format: 'int32',
        },
        {
            name: 'numItems',
            baseName: 'numItems',
            type: 'number',
            format: 'int32',
        },
        {
            name: 'notifications',
            baseName: 'notifications',
            type: 'Array<Alarm>',
            format: '',
        },
    ];

    /**
     * Returns the attribute type map.
     */
    static getAttributeTypeMap(): Array<{ name: string; baseName: string; type: string; format: string }> {
        return AlarmsPaged.attributeTypeMap;
    }

    /**
     * Constructs a new instance of the AlarmsPaged class.
     */
    public constructor() {}
}
