/**
 * myUplink Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class AvailableMethods {
    'settings'?: boolean;
    'reboot'?: boolean;
    'forcesync'?: boolean;
    'forceUpdate'?: boolean;
    'requestUpdate'?: boolean;
    'resetAlarm'?: boolean;
    'triggerEvent'?: boolean;
    'getMenu'?: boolean;
    'getMenuChain'?: boolean;
    'getGuideQuestion'?: boolean;
    'sendHaystack'?: boolean;
    'setSmartMode'?: boolean;
    'setAidMode'?: boolean;
    'getZones'?: boolean;
    'processIntent'?: boolean;
    'boostHotWater'?: boolean;
    'boostVentilation'?: boolean;
    'getScheduleConfig'?: boolean;
    'getScheduleModes'?: boolean;
    'getScheduleWeekly'?: boolean;
    'getScheduleVacation'?: boolean;
    'setScheduleModes'?: boolean;
    'setScheduleWeekly'?: boolean;
    'setScheduleOverride'?: boolean;
    'setScheduleVacation'?: boolean;
    'setVentilationMode'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
        {
            name: 'settings',
            baseName: 'settings',
            type: 'boolean',
            format: '',
        },
        {
            name: 'reboot',
            baseName: 'reboot',
            type: 'boolean',
            format: '',
        },
        {
            name: 'forcesync',
            baseName: 'forcesync',
            type: 'boolean',
            format: '',
        },
        {
            name: 'forceUpdate',
            baseName: 'forceUpdate',
            type: 'boolean',
            format: '',
        },
        {
            name: 'requestUpdate',
            baseName: 'requestUpdate',
            type: 'boolean',
            format: '',
        },
        {
            name: 'resetAlarm',
            baseName: 'resetAlarm',
            type: 'boolean',
            format: '',
        },
        {
            name: 'triggerEvent',
            baseName: 'triggerEvent',
            type: 'boolean',
            format: '',
        },
        {
            name: 'getMenu',
            baseName: 'getMenu',
            type: 'boolean',
            format: '',
        },
        {
            name: 'getMenuChain',
            baseName: 'getMenuChain',
            type: 'boolean',
            format: '',
        },
        {
            name: 'getGuideQuestion',
            baseName: 'getGuideQuestion',
            type: 'boolean',
            format: '',
        },
        {
            name: 'sendHaystack',
            baseName: 'sendHaystack',
            type: 'boolean',
            format: '',
        },
        {
            name: 'setSmartMode',
            baseName: 'setSmartMode',
            type: 'boolean',
            format: '',
        },
        {
            name: 'setAidMode',
            baseName: 'setAidMode',
            type: 'boolean',
            format: '',
        },
        {
            name: 'getZones',
            baseName: 'getZones',
            type: 'boolean',
            format: '',
        },
        {
            name: 'processIntent',
            baseName: 'processIntent',
            type: 'boolean',
            format: '',
        },
        {
            name: 'boostHotWater',
            baseName: 'boostHotWater',
            type: 'boolean',
            format: '',
        },
        {
            name: 'boostVentilation',
            baseName: 'boostVentilation',
            type: 'boolean',
            format: '',
        },
        {
            name: 'getScheduleConfig',
            baseName: 'getScheduleConfig',
            type: 'boolean',
            format: '',
        },
        {
            name: 'getScheduleModes',
            baseName: 'getScheduleModes',
            type: 'boolean',
            format: '',
        },
        {
            name: 'getScheduleWeekly',
            baseName: 'getScheduleWeekly',
            type: 'boolean',
            format: '',
        },
        {
            name: 'getScheduleVacation',
            baseName: 'getScheduleVacation',
            type: 'boolean',
            format: '',
        },
        {
            name: 'setScheduleModes',
            baseName: 'setScheduleModes',
            type: 'boolean',
            format: '',
        },
        {
            name: 'setScheduleWeekly',
            baseName: 'setScheduleWeekly',
            type: 'boolean',
            format: '',
        },
        {
            name: 'setScheduleOverride',
            baseName: 'setScheduleOverride',
            type: 'boolean',
            format: '',
        },
        {
            name: 'setScheduleVacation',
            baseName: 'setScheduleVacation',
            type: 'boolean',
            format: '',
        },
        {
            name: 'setVentilationMode',
            baseName: 'setVentilationMode',
            type: 'boolean',
            format: '',
        },
    ];

    static getAttributeTypeMap(): Array<{ name: string; baseName: string; type: string; format: string }> {
        return AvailableMethods.attributeTypeMap;
    }

    public constructor() {}
}
