/**
 * myUplink Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Device data point.
 */
export class DataPoint {
    /**
     * Timestamp property.
     */
    'timestamp'?: Date;
    /**
     * Value property.
     */
    'value'?: number | null;
    /**
     * The id of the device variable.
     */
    'pointId'?: string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
        {
            name: 'timestamp',
            baseName: 'timestamp',
            type: 'Date',
            format: 'date-time',
        },
        {
            name: 'value',
            baseName: 'value',
            type: 'number',
            format: 'double',
        },
        {
            name: 'pointId',
            baseName: 'pointId',
            type: 'string',
            format: '',
        },
    ];

    static getAttributeTypeMap(): Array<{ name: string; baseName: string; type: string; format: string }> {
        return DataPoint.attributeTypeMap;
    }

    public constructor() {}
}
