/**
 * myUplink Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { PremiumFeatureResponseModel } from '../models/PremiumFeatureResponseModel';

/**
 * Represents the response for device premium features.
 */
export class DevicePremiumResponse {
    'subscriptions'?: Array<PremiumFeatureResponseModel> | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
        {
            name: 'subscriptions',
            baseName: 'subscriptions',
            type: 'Array<PremiumFeatureResponseModel>',
            format: '',
        },
    ];

    /**
     * Returns the attribute type map for DevicePremiumResponse.
     */
    static getAttributeTypeMap(): Array<{ name: string; baseName: string; type: string; format: string }> {
        return DevicePremiumResponse.attributeTypeMap;
    }

    /**
     * Constructs a new instance of the DevicePremiumResponse class.
     */
    public constructor() {}
}
