/**
 * myUplink Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ParameterDetail } from '../models/ParameterDetail';

/**
 * Equip model.
 */
export class DeviceCategory {
    /**
     * Category name.
     */
    'categoryName'?: string | null;
    /**
     * Parameters.
     */
    'parameters'?: Array<ParameterDetail> | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
        {
            name: 'categoryName',
            baseName: 'categoryName',
            type: 'string',
            format: '',
        },
        {
            name: 'parameters',
            baseName: 'parameters',
            type: 'Array<ParameterDetail>',
            format: '',
        },
    ];

    static getAttributeTypeMap() {
        return DeviceCategory.attributeTypeMap;
    }

    public constructor() {}
}
