/**
 * myUplink Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Grouped parameter value.
 */
export class DeviceParameterData {
    /**
     * Parameter id.
     */
    'parameterId'?: string | null;
    /**
     * Parameter name.
     */
    'parameterName'?: string | null;
    /**
     * Parameter unit.
     */
    'parameterUnit'?: string | null;
    /**
     * Device id.
     */
    'deviceId'?: string | null;
    /**
     * Timestamp property.
     */
    'timestamp'?: Date;
    /**
     * Value property.
     */
    'value'?: number | null;
    /**
     * String value property.
     */
    'strVal'?: string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
        {
            name: 'parameterId',
            baseName: 'parameterId',
            type: 'string',
            format: '',
        },
        {
            name: 'parameterName',
            baseName: 'parameterName',
            type: 'string',
            format: '',
        },
        {
            name: 'parameterUnit',
            baseName: 'parameterUnit',
            type: 'string',
            format: '',
        },
        {
            name: 'deviceId',
            baseName: 'deviceId',
            type: 'string',
            format: '',
        },
        {
            name: 'timestamp',
            baseName: 'timestamp',
            type: 'Date',
            format: 'date-time',
        },
        {
            name: 'value',
            baseName: 'value',
            type: 'number',
            format: 'double',
        },
        {
            name: 'strVal',
            baseName: 'strVal',
            type: 'string',
            format: '',
        },
    ];

    /**
     * Returns the attribute type map for DeviceParameterData.
     */
    static getAttributeTypeMap(): Array<{ name: string; baseName: string; type: string; format: string }> {
        return DeviceParameterData.attributeTypeMap;
    }

    /**
     * Constructs a new instance of the DeviceParameterData class.
     */
    public constructor() {}
}
