/**
 * myUplink Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Specifies the different connection states of a device.  0 - Disconnected  1 - Connected
 */
export enum DeviceConnectionState {
    Disconnected = 'Disconnected',
    Connected = 'Connected',
}
