/**
 * myUplink Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Class representing EnumValues.
 */
export class EnumValues {
    /**
     * The EnumValue of the Enum.
     */
    'value'?: string | null;
    /**
     * The EnumText of the Enum.
     */
    'text'?: string | null;
    /**
     * The EnumIcon of the Enum.
     */
    'icon'?: string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
        {
            name: 'value',
            baseName: 'value',
            type: 'string',
            format: '',
        },
        {
            name: 'text',
            baseName: 'text',
            type: 'string',
            format: '',
        },
        {
            name: 'icon',
            baseName: 'icon',
            type: 'string',
            format: '',
        },
    ];

    /**
     * Returns the attribute type map for EnumValues.
     */
    static getAttributeTypeMap(): Array<{ name: string; baseName: string; type: string; format: string }> {
        return EnumValues.attributeTypeMap;
    }

    /**
     * Constructs an instance of EnumValues.
     */
    public constructor() {}
}
