/**
 * myUplink Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DeviceParameterData } from '../models/DeviceParameterData';

/**
 * Grouped parameter value.
 */
export class GroupedDeviceParameterData {
    /**
     * Category name.
     */
    'categoryName'?: string | null;
    /**
     * Device parameter data.
     */
    'parameters'?: Array<DeviceParameterData> | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
        {
            name: 'categoryName',
            baseName: 'categoryName',
            type: 'string',
            format: '',
        },
        {
            name: 'parameters',
            baseName: 'parameters',
            type: 'Array<DeviceParameterData>',
            format: '',
        },
    ];

    static getAttributeTypeMap(): Array<{ name: string; baseName: string; type: string; format: string }> {
        return GroupedDeviceParameterData.attributeTypeMap;
    }

    public constructor() {}
}
