/**
 * myUplink Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { EnumValues } from '../models/EnumValues';

/**
 * Equip group model.
 */
export class ParameterDetail {
    /**
     * Parameter id.
     */
    'parameterId'?: string | null;
    /**
     * Parameter name.
     */
    'parameterName'?: string | null;
    /**
     * Parameter unit.
     */
    'parameterUnit'?: string | null;
    /**
     * Parameter Smart home categories.
     */
    'smartHomeCategories'?: Array<string> | null;
    /**
     * Parameter min value.
     */
    'minValue'?: number | null;
    /**
     * Parameter max value.
     */
    'maxValue'?: number | null;
    /**
     * Parameter step value, specifies the allowed stepping between valid values  when the value is numeric.
     */
    'stepValue'?: number | null;
    /**
     * Parameter enum values.
     */
    'enumValues'?: Array<EnumValues> | null;
    /**
     * Parameter scale value.
     */
    'scaleValue'?: string | null;
    /**
     * Reference to a ShZone entity.
     */
    'zoneId'?: string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
        {
            name: 'parameterId',
            baseName: 'parameterId',
            type: 'string',
            format: '',
        },
        {
            name: 'parameterName',
            baseName: 'parameterName',
            type: 'string',
            format: '',
        },
        {
            name: 'parameterUnit',
            baseName: 'parameterUnit',
            type: 'string',
            format: '',
        },
        {
            name: 'smartHomeCategories',
            baseName: 'smartHomeCategories',
            type: 'Array<string>',
            format: '',
        },
        {
            name: 'minValue',
            baseName: 'minValue',
            type: 'number',
            format: 'int32',
        },
        {
            name: 'maxValue',
            baseName: 'maxValue',
            type: 'number',
            format: 'int32',
        },
        {
            name: 'stepValue',
            baseName: 'stepValue',
            type: 'number',
            format: 'int32',
        },
        {
            name: 'enumValues',
            baseName: 'enumValues',
            type: 'Array<EnumValues>',
            format: '',
        },
        {
            name: 'scaleValue',
            baseName: 'scaleValue',
            type: 'string',
            format: '',
        },
        {
            name: 'zoneId',
            baseName: 'zoneId',
            type: 'string',
            format: '',
        },
    ];

    static getAttributeTypeMap() {
        return ParameterDetail.attributeTypeMap;
    }

    public constructor() {}
}
