/**
 * myUplink Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Patch group request.
 */
export class PatchSystemModel {
    /**
     * Id.
     */
    'systemId'?: string;
    /**
     * Name.
     */
    'name'?: string | null;
    /**
     * Is found.
     */
    'isFound'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
        {
            name: 'systemId',
            baseName: 'systemId',
            type: 'string',
            format: 'uuid',
        },
        {
            name: 'name',
            baseName: 'name',
            type: 'string',
            format: '',
        },
        {
            name: 'isFound',
            baseName: 'isFound',
            type: 'boolean',
            format: '',
        },
    ];

    static getAttributeTypeMap(): Array<{ name: string; baseName: string; type: string; format: string }> {
        return PatchSystemModel.attributeTypeMap;
    }

    public constructor() {}
}
