/**
 * myUplink Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PremiumFeatures } from '../models/PremiumFeatures';

export class PremiumFeatureResponseModel {
    'validUntil'?: Date | null;
    'type'?: PremiumFeatures;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
        {
            name: 'validUntil',
            baseName: 'validUntil',
            type: 'Date',
            format: 'date-time',
        },
        {
            name: 'type',
            baseName: 'type',
            type: 'PremiumFeatures',
            format: '',
        },
    ];

    static getAttributeTypeMap(): Array<{ name: string; baseName: string; type: string; format: string }> {
        return PremiumFeatureResponseModel.attributeTypeMap;
    }

    public constructor() {}
}
