/**
 * myUplink Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Country } from '../models/Country';

/**
 * Represents the address for product registration.
 */
export class ProductRegistrationAddress {
    'city'?: string | null;
    'region'?: string | null;
    'country'?: Country;
    'postalCode'?: string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
        {
            name: 'city',
            baseName: 'city',
            type: 'string',
            format: '',
        },
        {
            name: 'region',
            baseName: 'region',
            type: 'string',
            format: '',
        },
        {
            name: 'country',
            baseName: 'country',
            type: 'Country',
            format: '',
        },
        {
            name: 'postalCode',
            baseName: 'postalCode',
            type: 'string',
            format: '',
        },
    ];

    /**
     * Returns the attribute type map for ProductRegistrationAddress.
     */
    static getAttributeTypeMap(): Array<{ name: string; baseName: string; type: string; format: string }> {
        return ProductRegistrationAddress.attributeTypeMap;
    }

    /**
     * Constructs a new instance of the ProductRegistrationAddress class.
     */
    public constructor() {}
}
