/**
 * myUplink Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * ProductResponseModel
 */
export class ProductResponseModel {
    /**
     * SerialNumber
     */
    'serialNumber'?: string | null;
    /**
     * Name
     */
    'name'?: string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
        {
            name: 'serialNumber',
            baseName: 'serialNumber',
            type: 'string',
            format: '',
        },
        {
            name: 'name',
            baseName: 'name',
            type: 'string',
            format: '',
        },
    ];

    /**
     * Returns the attribute type map for ProductResponseModel.
     */
    static getAttributeTypeMap(): Array<{ name: string; baseName: string; type: string; format: string }> {
        return ProductResponseModel.attributeTypeMap;
    }

    /**
     * Constructs a new instance of the ProductResponseModel class.
     */
    public constructor() {}
}
