/**
 * myUplink Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ReportedFirmware } from '../models/ReportedFirmware';

export class Reported {
    'deviceName'?: string | null;
    'productName'?: string | null;
    'brand'?: string | null;
    'version'?: string | null;
    'serialId'?: string | null;
    'firmware'?: ReportedFirmware;
    'aidMode'?: string | null;
    'smartMode'?: string | null;
    'country'?: string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
        {
            name: 'deviceName',
            baseName: 'deviceName',
            type: 'string',
            format: '',
        },
        {
            name: 'productName',
            baseName: 'productName',
            type: 'string',
            format: '',
        },
        {
            name: 'brand',
            baseName: 'brand',
            type: 'string',
            format: '',
        },
        {
            name: 'version',
            baseName: 'version',
            type: 'string',
            format: '',
        },
        {
            name: 'serialId',
            baseName: 'serialId',
            type: 'string',
            format: '',
        },
        {
            name: 'firmware',
            baseName: 'firmware',
            type: 'ReportedFirmware',
            format: '',
        },
        {
            name: 'aidMode',
            baseName: 'aidMode',
            type: 'string',
            format: '',
        },
        {
            name: 'smartMode',
            baseName: 'smartMode',
            type: 'string',
            format: '',
        },
        {
            name: 'country',
            baseName: 'country',
            type: 'string',
            format: '',
        },
        {
            name: 'version',
            baseName: '$version',
            type: 'string',
            format: '',
        },
    ];

    static getAttributeTypeMap(): Array<{ name: string; baseName: string; type: string; format: string }> {
        return Reported.attributeTypeMap;
    }

    public constructor() {}
}
