/**
 * myUplink Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Properties } from '../models/Properties';

export class SearchGroupSSG {
    'deviceId'?: string | null;
    'systemId'?: string | null;
    'version'?: number | null;
    'status'?: string | null;
    'connectionState'?: string | null;
    'lastActivityTime'?: Date;
    'authenticationType'?: string | null;
    'properties'?: Properties;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
        {
            name: 'deviceId',
            baseName: 'deviceId',
            type: 'string',
            format: '',
        },
        {
            name: 'systemId',
            baseName: 'systemId',
            type: 'string',
            format: 'uuid',
        },
        {
            name: 'version',
            baseName: 'version',
            type: 'number',
            format: 'int64',
        },
        {
            name: 'status',
            baseName: 'status',
            type: 'string',
            format: '',
        },
        {
            name: 'connectionState',
            baseName: 'connectionState',
            type: 'string',
            format: '',
        },
        {
            name: 'lastActivityTime',
            baseName: 'lastActivityTime',
            type: 'Date',
            format: 'date-time',
        },
        {
            name: 'authenticationType',
            baseName: 'authenticationType',
            type: 'string',
            format: '',
        },
        {
            name: 'properties',
            baseName: 'properties',
            type: 'Properties',
            format: '',
        },
    ];

    static getAttributeTypeMap() {
        return SearchGroupSSG.attributeTypeMap;
    }

    public constructor() {}
}
