/**
 * myUplink Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Smart mode enum.
 */
export enum SmartMode {
    Default = 'Default',
    Normal = 'Normal',
    Away = 'Away',
    Vacation = 'Vacation',
    Home = 'Home',
}
