/**
 * myUplink Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Ssq group device.
 */
export class SsqGroupDevice {
    /**
     * Name.
     */
    'name'?: string | null;
    /**
     * Description.
     */
    'description'?: string | null;
    /**
     * Device Id.
     */
    'id'?: string | null;
    /**
     * Type.
     */
    'type'?: string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
        {
            name: 'name',
            baseName: 'name',
            type: 'string',
            format: '',
        },
        {
            name: 'description',
            baseName: 'description',
            type: 'string',
            format: '',
        },
        {
            name: 'id',
            baseName: 'id',
            type: 'string',
            format: '',
        },
        {
            name: 'type',
            baseName: 'type',
            type: 'string',
            format: '',
        },
    ];

    /**
     * Get the attribute type map.
     *
     * @returns Array of attribute type map objects.
     */
    static getAttributeTypeMap(): Array<{ name: string; baseName: string; type: string; format: string }> {
        return SsqGroupDevice.attributeTypeMap;
    }

    /**
     * Constructs a new instance of the SsqGroupDevice class.
     */
    public constructor() {}
}
