/**
 * myUplink Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export enum Status {
    None = 'None',
    Active = 'Active',
    DismissedByDevice = 'DismissedByDevice',
    ResetByUserOnDevice = 'ResetByUserOnDevice',
    ResetByUserFromCloud = 'ResetByUserFromCloud',
    Unknown = 'Unknown',
}
