/**
 * myUplink Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { StoreSetEntry } from '../models/StoreSetEntry';

/**
 * Represents a set of stores with a title and rows of entries.
 */
export class StoreSet {
    'title'?: string | null;
    'rows'?: Array<StoreSetEntry> | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
        {
            name: 'title',
            baseName: 'title',
            type: 'string',
            format: '',
        },
        {
            name: 'rows',
            baseName: 'rows',
            type: 'Array<StoreSetEntry>',
            format: '',
        },
    ];

    /**
     * Returns the attribute type map for the StoreSet class.
     */
    static getAttributeTypeMap(): Array<{ name: string; baseName: string; type: string; format: string }> {
        return StoreSet.attributeTypeMap;
    }

    /**
     * Constructs a new instance of the StoreSet class.
     */
    public constructor() {}
}
