/**
 * myUplink Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Represents an entry in the store set.
 */
export class StoreSetEntry {
    'variableId'?: string | null;
    'description'?: string | null;
    'currentValue'?: number;
    'defaultValue'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
        {
            name: 'variableId',
            baseName: 'variableId',
            type: 'string',
            format: '',
        },
        {
            name: 'description',
            baseName: 'description',
            type: 'string',
            format: '',
        },
        {
            name: 'currentValue',
            baseName: 'currentValue',
            type: 'number',
            format: 'int32',
        },
        {
            name: 'defaultValue',
            baseName: 'defaultValue',
            type: 'number',
            format: 'int32',
        },
    ];

    /**
     * Returns the attribute type map for StoreSetEntry.
     */
    static getAttributeTypeMap(): Array<{ name: string; baseName: string; type: string; format: string }> {
        return StoreSetEntry.attributeTypeMap;
    }

    /**
     * Constructs a new instance of StoreSetEntry.
     */
    public constructor() {}
}
