/**
 * myUplink Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { SecurityLevel } from '../models/SecurityLevel';
import type { SystemDevice } from '../models/SystemDevice';

/**
 * Group.
 */
export class SystemWithDevices {
    /**
     * System identifier.
     */
    'systemId'?: string;
    /**
     * System name.
     */
    'name'?: string | null;
    'securityLevel'?: SecurityLevel;
    /**
     * Whether system currently has an active alarm.
     */
    'hasAlarm'?: boolean;
    /**
     * System country.
     */
    'country'?: string | null;
    /**
     * List of devices.
     */
    'devices'?: Array<SystemDevice> | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
        {
            name: 'systemId',
            baseName: 'systemId',
            type: 'string',
            format: 'uuid',
        },
        {
            name: 'name',
            baseName: 'name',
            type: 'string',
            format: '',
        },
        {
            name: 'securityLevel',
            baseName: 'securityLevel',
            type: 'SecurityLevel',
            format: '',
        },
        {
            name: 'hasAlarm',
            baseName: 'hasAlarm',
            type: 'boolean',
            format: '',
        },
        {
            name: 'country',
            baseName: 'country',
            type: 'string',
            format: '',
        },
        {
            name: 'devices',
            baseName: 'devices',
            type: 'Array<SystemDevice>',
            format: '',
        },
    ];

    /**
     * Returns the attribute type map for SystemWithDevices.
     */
    static getAttributeTypeMap(): Array<{ name: string; baseName: string; type: string; format: string }> {
        return SystemWithDevices.attributeTypeMap;
    }

    /**
     * Constructs a new instance of the SystemWithDevices class.
     */
    public constructor() {}
}
