/**
 * myUplink Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class V2DevicesDeviceIdSmartHomeCategoriesGet200Response {
    'shEnergyMetered'?: boolean;
    'shHwBoost'?: boolean;
    'shHwTemp'?: boolean;
    'shIndoorCO2'?: boolean;
    'shIndoorHumidity'?: boolean;
    'shIndoorSpHeat'?: boolean;
    'shIndoorSpCool'?: boolean;
    'shIndoorSpOffsHeat'?: boolean;
    'shIndoorSpOffsCool'?: boolean;
    'shIndoorTemp'?: boolean;
    'shOutdoorTemp'?: boolean;
    'shPoolTemp'?: boolean;
    'shReturnTemp'?: boolean;
    'shSmartMode'?: boolean;
    'shSolarEnergyProducedDay'?: boolean;
    'shSolarEnergyProducedWeek'?: boolean;
    'shSolarEnergyProducedMonth'?: boolean;
    'shSolarEnergyProducedYear'?: boolean;
    'shSolarEnergyProducedTotal'?: boolean;
    'shSupplyTemp'?: boolean;
    'shVentBoost'?: boolean;
    'shVentMode'?: boolean;
    'shZones'?: boolean;
    'shZoneMode'?: boolean;
    'shElectricPowerUsedCurrently'?: boolean;
    'shHwMode'?: boolean;
    'shIndoorCO2Sp'?: boolean;
    'shIndoorHumiditySp'?: boolean;
    'shPoolSp'?: boolean;
    'shSolarPowerAvailableCurrently'?: boolean;
    'shElectricalPriceMode'?: boolean;
    'shElectricalPriceModeDuration'?: boolean;
    'shIndoorHumidityMode'?: boolean;
    'shIndoorDeHumiditySp'?: boolean;
    'shFanMode'?: boolean;
    'shFanStatus'?: boolean;
    'shEnergyStateOfCharge'?: boolean;
    'shEnergyMeteredDay'?: boolean;
    'shEnergyMeteredMonth'?: boolean;
    'shEnergyMeteredYear'?: boolean;
    'shElectricalPriceNextLow'?: boolean;
    'shElectricalPriceNextHigh'?: boolean;
    'shHeatMode'?: boolean;
    'shHeatBoost'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
        {
            name: 'shEnergyMetered',
            baseName: 'sh-energyMetered',
            type: 'boolean',
            format: '',
        },
        {
            name: 'shHwBoost',
            baseName: 'sh-hwBoost',
            type: 'boolean',
            format: '',
        },
        {
            name: 'shHwTemp',
            baseName: 'sh-hwTemp',
            type: 'boolean',
            format: '',
        },
        {
            name: 'shIndoorCO2',
            baseName: 'sh-indoorCO2',
            type: 'boolean',
            format: '',
        },
        {
            name: 'shIndoorHumidity',
            baseName: 'sh-indoorHumidity',
            type: 'boolean',
            format: '',
        },
        {
            name: 'shIndoorSpHeat',
            baseName: 'sh-indoorSpHeat',
            type: 'boolean',
            format: '',
        },
        {
            name: 'shIndoorSpCool',
            baseName: 'sh-indoorSpCool',
            type: 'boolean',
            format: '',
        },
        {
            name: 'shIndoorSpOffsHeat',
            baseName: 'sh-indoorSpOffsHeat',
            type: 'boolean',
            format: '',
        },
        {
            name: 'shIndoorSpOffsCool',
            baseName: 'sh-indoorSpOffsCool',
            type: 'boolean',
            format: '',
        },
        {
            name: 'shIndoorTemp',
            baseName: 'sh-indoorTemp',
            type: 'boolean',
            format: '',
        },
        {
            name: 'shOutdoorTemp',
            baseName: 'sh-outdoorTemp',
            type: 'boolean',
            format: '',
        },
        {
            name: 'shPoolTemp',
            baseName: 'sh-poolTemp',
            type: 'boolean',
            format: '',
        },
        {
            name: 'shReturnTemp',
            baseName: 'sh-returnTemp',
            type: 'boolean',
            format: '',
        },
        {
            name: 'shSmartMode',
            baseName: 'sh-smartMode',
            type: 'boolean',
            format: '',
        },
        {
            name: 'shSolarEnergyProducedDay',
            baseName: 'sh-solarEnergyProducedDay',
            type: 'boolean',
            format: '',
        },
        {
            name: 'shSolarEnergyProducedWeek',
            baseName: 'sh-solarEnergyProducedWeek',
            type: 'boolean',
            format: '',
        },
        {
            name: 'shSolarEnergyProducedMonth',
            baseName: 'sh-solarEnergyProducedMonth',
            type: 'boolean',
            format: '',
        },
        {
            name: 'shSolarEnergyProducedYear',
            baseName: 'sh-solarEnergyProducedYear',
            type: 'boolean',
            format: '',
        },
        {
            name: 'shSolarEnergyProducedTotal',
            baseName: 'sh-solarEnergyProducedTotal',
            type: 'boolean',
            format: '',
        },
        {
            name: 'shSupplyTemp',
            baseName: 'sh-supplyTemp',
            type: 'boolean',
            format: '',
        },
        {
            name: 'shVentBoost',
            baseName: 'sh-ventBoost',
            type: 'boolean',
            format: '',
        },
        {
            name: 'shVentMode',
            baseName: 'sh-ventMode',
            type: 'boolean',
            format: '',
        },
        {
            name: 'shZones',
            baseName: 'sh-zones',
            type: 'boolean',
            format: '',
        },
        {
            name: 'shZoneMode',
            baseName: 'sh-zoneMode',
            type: 'boolean',
            format: '',
        },
        {
            name: 'shElectricPowerUsedCurrently',
            baseName: 'sh-electricPowerUsedCurrently',
            type: 'boolean',
            format: '',
        },
        {
            name: 'shHwMode',
            baseName: 'sh-hwMode',
            type: 'boolean',
            format: '',
        },
        {
            name: 'shIndoorCO2Sp',
            baseName: 'sh-indoorCO2Sp',
            type: 'boolean',
            format: '',
        },
        {
            name: 'shIndoorHumiditySp',
            baseName: 'sh-indoorHumiditySp',
            type: 'boolean',
            format: '',
        },
        {
            name: 'shPoolSp',
            baseName: 'sh-poolSp',
            type: 'boolean',
            format: '',
        },
        {
            name: 'shSolarPowerAvailableCurrently',
            baseName: 'sh-solarPowerAvailableCurrently',
            type: 'boolean',
            format: '',
        },
        {
            name: 'shElectricalPriceMode',
            baseName: 'sh-electricalPriceMode',
            type: 'boolean',
            format: '',
        },
        {
            name: 'shElectricalPriceModeDuration',
            baseName: 'sh-electricalPriceModeDuration',
            type: 'boolean',
            format: '',
        },
        {
            name: 'shIndoorHumidityMode',
            baseName: 'sh-indoorHumidityMode',
            type: 'boolean',
            format: '',
        },
        {
            name: 'shIndoorDeHumiditySp',
            baseName: 'sh-indoorDeHumiditySp',
            type: 'boolean',
            format: '',
        },
        {
            name: 'shFanMode',
            baseName: 'sh-fanMode',
            type: 'boolean',
            format: '',
        },
        {
            name: 'shFanStatus',
            baseName: 'sh-fanStatus',
            type: 'boolean',
            format: '',
        },
        {
            name: 'shEnergyStateOfCharge',
            baseName: 'sh-energyStateOfCharge',
            type: 'boolean',
            format: '',
        },
        {
            name: 'shEnergyMeteredDay',
            baseName: 'sh-energyMeteredDay',
            type: 'boolean',
            format: '',
        },
        {
            name: 'shEnergyMeteredMonth',
            baseName: 'sh-energyMeteredMonth',
            type: 'boolean',
            format: '',
        },
        {
            name: 'shEnergyMeteredYear',
            baseName: 'sh-energyMeteredYear',
            type: 'boolean',
            format: '',
        },
        {
            name: 'shElectricalPriceNextLow',
            baseName: 'sh-electricalPriceNextLow',
            type: 'boolean',
            format: '',
        },
        {
            name: 'shElectricalPriceNextHigh',
            baseName: 'sh-electricalPriceNextHigh',
            type: 'boolean',
            format: '',
        },
        {
            name: 'shHeatMode',
            baseName: 'sh-heatMode',
            type: 'boolean',
            format: '',
        },
        {
            name: 'shHeatBoost',
            baseName: 'sh-heatBoost',
            type: 'boolean',
            format: '',
        },
    ];

    static getAttributeTypeMap(): Array<{ name: string; baseName: string; type: string; format: string }> {
        return V2DevicesDeviceIdSmartHomeCategoriesGet200Response.attributeTypeMap;
    }

    public constructor() {}
}
