/**
 * myUplink Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VoucherType } from '../models/VoucherType';

/**
 * Voucher single request.
 */
export class VoucherManyRequest {
    /**
     * Num days.
     */
    'numDays'?: number;
    'voucherType'?: VoucherType;
    /**
     * Serial number.
     */
    'numVouchers'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
        {
            name: 'numDays',
            baseName: 'numDays',
            type: 'number',
            format: 'int32',
        },
        {
            name: 'voucherType',
            baseName: 'voucherType',
            type: 'VoucherType',
            format: '',
        },
        {
            name: 'numVouchers',
            baseName: 'numVouchers',
            type: 'number',
            format: 'int32',
        },
    ];

    static getAttributeTypeMap() {
        return VoucherManyRequest.attributeTypeMap;
    }

    public constructor() {}
}
